name: Go

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  draft-release:
    runs-on: ubuntu-latest
    steps:
      - name: Create draft release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
  release:
    runs-on: ubuntu-latest
    needs: draft-release
    strategy:
      matrix:
        GOOS: [linux, darwin, windows]
        GOARCH: [amd64, arm64]

    steps:
      - uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.25"

      - name: Install dependencies
        run: go get .

      - name: Build
        run: GOOS=${{ matrix.GOOS }} GOARCH=${{ matrix.GOARCH }} go build -o aoi-dono-${{ matrix.GOOS }}-${{ matrix.GOARCH }} -v ./...

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          files: aoi-dono-${{ matrix.GOOS }}-${{ matrix.GOARCH }}
